# Generated by Django 5.0.7 on 2024-08-23 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflansapp', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_form_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer_name', models.TextField(max_length=64)),
                ('customer_email', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='customer_email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='customer_name',
            field=models.TextField(max_length=64),
        ),
    ]
