# Generated by Django 5.0.7 on 2024-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlyflansapp', '0003_loginform_alter_contactform_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='detalle_contacto',
            field=models.CharField(default=11111, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
